//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kafe_Kahve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int id { get; set; }
        public string k_adi { get; set; }
        public string sifre { get; set; }
        public Nullable<bool> role { get; set; }
    }
}
